;;; Install the melpa archive in emacs
(require 'melpa)
(require 'looks)
(require 'basic-functionality)
(require 'whitespace-setup)
(require 'magit-setup)
(require 'multiple-cursors-setup)
(require 'company-setup)
(require 'ruby-setup)
(require 'rust-setup)
(require 'elm-setup)
(require 'hy-setup)

(defun submacs-version ()
    (message "0.3a"))
(provide 'submacs-init)
